### ISSUE TITLE
可以在petalinux上识别到块设备吗

### ISSUE THREAD

**Issue by joshuafc** [lizhirui/AXI-SDCard-High-Speed-Controller#4]
能否用于petalinux系统的根文件系统

**Comment by lizhirui** [comment]
这个模块没有针对随机访问优化，然后就是驱动程序得要你自己写（



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月27日 18:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [lizhirui/AXI-SDCard-High-Speed-Controller] 可以在petalinux上识别到块设备吗 (Issue #4) |

能否用于petalinux系统的根文件系统

**Comment by joshuafc** [comment]
谢谢
